In [10]:
import pandas as pd
file_path = "../Data/data.jsonl"

# Load JSONL
df = pd.read_json(file_path, lines=True)
print("Shape:", df.shape)
df.head()

Shape: (8799, 2)

  kind                                               data
0   t3  {'approved_at_utc': None, 'subreddit': 'Anarch...
1   t3  {'approved_at_utc': None, 'subreddit': 'Anarch...
2   t3  {'approved_at_utc': None, 'subreddit': 'Anarch...
3   t3  {'approved_at_utc': None, 'subreddit': 'Anarch...
4   t3  {'approved_at_utc': None, 'subreddit': 'Anarch...

In [2]:
print(df.info())
print(df.describe(include='all'))
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
Index: 8799 entries, 0 to 8798
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kind    8799 non-null   object
 1   data    8799 non-null   object
dtypes: object(2)
memory usage: 206.2+ KB
None
        kind                                               data
count   8799                                               8799
unique     1                                               8799
top       t3  {'approved_at_utc': None, 'subreddit': 'Anarch...
freq    8799                                                  1
Index(['kind', 'data'], dtype='object')

In [3]:
df['data'][0]

{'approved_at_utc': None,
 'subreddit': 'Anarchism',
 'selftext': ' What you are reading, watching, or listening to? Or how far have you gotten in your chosen selection since last week?',
 'author_fullname': 't2_6l4z3',
 'saved': False,
 'mod_reason_title': None,
 'gilded': 0,
 'clicked': False,
 'title': 'What Are You Reading/Book Club Tuesday',
 'link_flair_richtext': [],
 'subreddit_name_prefixed': 'r/Anarchism',
 'hidden': False,
 'pwls': None,
 'link_flair_css_class': None,
 'downs': 0,
 'thumbnail_height': None,
 'top_awarded_type': None,
 'hide_score': False,
 'name': 't3_1is5wgo',
 'quarantine': False,
 'link_flair_text_color': 'dark',
 'upvote_ratio': 1.0,
 'author_flair_background_color': None,
 'subreddit_type': 'public',
 'ups': 2,
 'total_awards_received': 0,
 'media_embed': {},
 'thumbnail_width': None,
 'author_flair_template_id': None,
 'is_original_content': False,
 'user_reports': [],
 'secure_media': None,
 'is_reddit_media_domain': False,
 'is_meta': False,
 'category': None,
 'secure_media_embed': {},
 'link_flair_text': None,
 'can_mod_post': False,
 'score': 2,
 'approved_by': None,
 'is_created_from_ads_ui': False,
 'author_premium': True,
 'thumbnail': 'self',
 'edited': False,
 'author_flair_css_class': None,
 'author_flair_richtext': [],
 'gildings': {},
 'content_categories': None,
 'is_self': True,
 'mod_note': None,
 'created': 1739858460.0,
 'link_flair_type': 'text',
 'wls': None,
 'removed_by_category': None,
 'banned_by': None,
 'author_flair_type': 'text',
 'domain': 'self.Anarchism',
 'allow_live_comments': False,
 'selftext_html': '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;What you are reading, watching, or listening to? Or how far have you gotten in your chosen selection since last week?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
 'likes': None,
 'suggested_sort': None,
 'banned_at_utc': None,
 'view_count': None,
 'archived': False,
 'no_follow': False,
 'is_crosspostable': False,
 'pinned': False,
 'over_18': False,
 'all_awardings': [],
 'awarders': [],
 'media_only': False,
 'can_gild': False,
 'spoiler': False,
 'locked': False,
 'author_flair_text': None,
 'treatment_tags': [],
 'visited': False,
 'removed_by': None,
 'num_reports': None,
 'distinguished': None,
 'subreddit_id': 't5_2qh5j',
 'author_is_blocked': False,
 'mod_reason_by': None,
 'removal_reason': None,
 'link_flair_background_color': '',
 'id': '1is5wgo',
 'is_robot_indexable': True,
 'report_reasons': None,
 'author': 'AutoModerator',
 'discussion_type': None,
 'num_comments': 1,
 'send_replies': False,
 'contest_mode': False,
 'mod_reports': [],
 'author_patreon_flair': False,
 'author_flair_text_color': None,
 'permalink': '/r/Anarchism/comments/1is5wgo/what_are_you_readingbook_club_tuesday/',
 'stickied': True,
 'url': 'https://www.reddit.com/r/Anarchism/comments/1is5wgo/what_are_you_readingbook_club_tuesday/',
 'subreddit_subscribers': 275979,
 'created_utc': 1739858460.0,
 'num_crossposts': 0,
 'media': None,
 'is_video': False}

In [4]:
df['data'][1000]

{'approved_at_utc': None,
 'subreddit': 'Conservative',
 'selftext': '',
 'author_fullname': 't2_avxx6',
 'saved': False,
 'mod_reason_title': None,
 'gilded': 0,
 'clicked': False,
 'title': 'Nolte: Disgraced ’60 Minutes’ Misleads Viewers on USAID Staff Reductions',
 'link_flair_richtext': [{'e': 'text', 't': 'Flaired Users Only'}],
 'subreddit_name_prefixed': 'r/Conservative',
 'hidden': False,
 'pwls': 7,
 'link_flair_css_class': 'CONSERVATIVESONLY',
 'downs': 0,
 'thumbnail_height': 73,
 'top_awarded_type': None,
 'hide_score': False,
 'name': 't3_1irsqvp',
 'quarantine': False,
 'link_flair_text_color': None,
 'upvote_ratio': 0.89,
 'author_flair_background_color': '',
 'subreddit_type': 'public',
 'ups': 14,
 'total_awards_received': 0,
 'media_embed': {},
 'thumbnail_width': 140,
 'author_flair_template_id': None,
 'is_original_content': False,
 'user_reports': [],
 'secure_media': None,
 'is_reddit_media_domain': False,
 'is_meta': False,
 'category': None,
 'secure_media_embed': {},
 'link_flair_text': 'Flaired Users Only',
 'can_mod_post': False,
 'score': 14,
 'approved_by': None,
 'is_created_from_ads_ui': False,
 'author_premium': False,
 'thumbnail': 'https://b.thumbs.redditmedia.com/RE_xCHBvU1hn9SoUxYHgZvKpvxVR4eArg3fzsC2vY4M.jpg',
 'edited': False,
 'author_flair_css_class': None,
 'author_flair_richtext': [{'e': 'text', 't': 'Unmitigated Conservative'}],
 'gildings': {},
 'post_hint': 'link',
 'content_categories': None,
 'is_self': False,
 'mod_note': None,
 'created': 1739821320.0,
 'link_flair_type': 'richtext',
 'wls': 7,
 'removed_by_category': None,
 'banned_by': None,
 'author_flair_type': 'richtext',
 'domain': 'breitbart.com',
 'allow_live_comments': False,
 'selftext_html': None,
 'likes': None,
 'suggested_sort': 'confidence',
 'banned_at_utc': None,
 'url_overridden_by_dest': 'https://www.breitbart.com/the-media/2025/02/17/nolte-disgraced-60-minutes-misleads-viewers-usaid-staff-reductions/',
 'view_count': None,
 'archived': False,
 'no_follow': False,
 'is_crosspostable': False,
 'pinned': False,
 'over_18': False,
 'preview': {'images': [{'source': {'url': 'https://external-preview.redd.it/26pDqpUfh1N3o0ha8bAtbND-VK9uUJKGbJywZ8fTTYY.jpg?auto=webp&amp;s=4f4d84a9e332d2c5b8ee217642e90d07435a2dba',
     'width': 640,
     'height': 335},
    'resolutions': [{'url': 'https://external-preview.redd.it/26pDqpUfh1N3o0ha8bAtbND-VK9uUJKGbJywZ8fTTYY.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=59f8162030521328aec57729e4511a1be5aa19fd',
      'width': 108,
      'height': 56},
     {'url': 'https://external-preview.redd.it/26pDqpUfh1N3o0ha8bAtbND-VK9uUJKGbJywZ8fTTYY.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=633fcfc76c8550bfed5c48687f96c0b8bb761ce1',
      'width': 216,
      'height': 113},
     {'url': 'https://external-preview.redd.it/26pDqpUfh1N3o0ha8bAtbND-VK9uUJKGbJywZ8fTTYY.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=e65e8ed8bc71b07aa3e471af44835f168ede78d1',
      'width': 320,
      'height': 167},
     {'url': 'https://external-preview.redd.it/26pDqpUfh1N3o0ha8bAtbND-VK9uUJKGbJywZ8fTTYY.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=2c5366f8a0bdabfd0796a8213b385f64d49771d0',
      'width': 640,
      'height': 335}],
    'variants': {},
    'id': 'p23hIPDJvCKwPyJAKO5DP1tgzNLMVIwZpUfNdX1p4GM'}],
  'enabled': False},
 'all_awardings': [],
 'awarders': [],
 'media_only': False,
 'can_gild': False,
 'spoiler': False,
 'locked': False,
 'author_flair_text': 'Unmitigated Conservative',
 'treatment_tags': [],
 'visited': False,
 'removed_by': None,
 'num_reports': None,
 'distinguished': None,
 'subreddit_id': 't5_2qh6p',
 'author_is_blocked': False,
 'mod_reason_by': None,
 'removal_reason': None,
 'link_flair_background_color': None,
 'id': '1irsqvp',
 'is_robot_indexable': True,
 'report_reasons': None,
 'author': 'M_i_c_K',
 'discussion_type': None,
 'num_comments': 1,
 'send_replies': True,
 'contest_mode': False,
 'mod_reports': [],
 'author_patreon_flair': False,
 'author_flair_text_color': 'dark',
 'permalink': '/r/Conservative/comments/1irsqvp/nolte_disgraced_60_minutes_misleads_viewers_on/',
 'stickied': False,
 'url': 'https://www.breitbart.com/the-media/2025/02/17/nolte-disgraced-60-minutes-misleads-viewers-usaid-staff-reductions/',
 'subreddit_subscribers': 1200167,
 'created_utc': 1739821320.0,
 'num_crossposts': 0,
 'media': None,
 'is_video': False}

In [11]:
df_flat = pd.json_normalize(df['data'], max_level=1)
df = df_flat 
df.head(10)

,approved_at_utc,subreddit,selftext,author_fullname,saved,mod_reason_title,gilded,clicked,title,link_flair_richtext,...,media_metadata.31amw8z1k0ae1,media_metadata.hj69o9w1k0ae1,media_metadata.rl6frk12k0ae1,media_metadata.6lftrf32k0ae1,media_metadata.uzzxzhe2k0ae1,media_metadata.h4jgntb2k0ae1,media_metadata.g1ehba82k0ae1,preview.reddit_video_preview,media_metadata.5myw07zahfbe1,media_metadata.yy02g3grph8e1
0,None,Anarchism,"What you are reading, watching, or listening ...",t2_6l4z3,False,None,0,False,What Are You Reading/Book Club Tuesday,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,Anarchism,,t2_4vt6saq5,False,None,0,False,"""WTF is Social Ecology?"" by Usufruct Collective",[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,Anarchism,I am an anarcho-nihilist and i am reading simi...,t2_1h2y206upy,False,None,0,False,Who do you think is the most powerful/popular ...,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,None,Anarchism,"Ayo, im an anarchist but perhaps not the most ...",t2_83t23peb,False,None,0,False,Not paying student loans or taxes,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,None,Anarchism,Looking for videos/podcasts/writing where folk...,t2_9haan,False,None,0,False,Recommendations for intellectual debate content,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,None,Anarchism,,t2_19lr7xlfsc,False,None,0,False,WE DONT WANT YOUR FUCKING WAR,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,None,Anarchism,Hey fellow anarcho from Germany here. Just wan...,t2_1fk20dsqjx,False,None,0,False,Links between german and us anarchism,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,None,Anarchism,,t2_gqmed92z0,False,None,0,False,Counter Protest TERFS in Brisbane QLD 10am 23r...,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,None,Anarchism,,t2_gp81eyi9,False,None,0,False,"For Presidents Day, rather than celebrating Ge...",[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,None,Anarchism,Have a mutual aid project you'd like to promot...,t2_6l4z3,False,None,0,False,Mutual Aid Monday,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df.columns

Index(['approved_at_utc', 'subreddit', 'selftext', 'author_fullname', 'saved',
       'mod_reason_title', 'gilded', 'clicked', 'title', 'link_flair_richtext',
       ...
       'media_metadata.31amw8z1k0ae1', 'media_metadata.hj69o9w1k0ae1',
       'media_metadata.rl6frk12k0ae1', 'media_metadata.6lftrf32k0ae1',
       'media_metadata.uzzxzhe2k0ae1', 'media_metadata.h4jgntb2k0ae1',
       'media_metadata.g1ehba82k0ae1', 'preview.reddit_video_preview',
       'media_metadata.5myw07zahfbe1', 'media_metadata.yy02g3grph8e1'],
      dtype='object', length=759)

In [41]:
df_temp = df

In [42]:
df_temp = df_temp.dropna(axis=1, thresh=len(df_temp)*0.1)

In [43]:
df_temp.shape

(8799, 85)

In [45]:
df = df_temp

In [46]:
df.columns

Index(['subreddit', 'selftext', 'author_fullname', 'saved', 'gilded',
       'clicked', 'title', 'link_flair_richtext', 'subreddit_name_prefixed',
       'hidden', 'pwls', 'link_flair_css_class', 'downs', 'thumbnail_height',
       'hide_score', 'name', 'quarantine', 'link_flair_text_color',
       'upvote_ratio', 'author_flair_background_color', 'subreddit_type',
       'ups', 'total_awards_received', 'thumbnail_width',
       'author_flair_template_id', 'is_original_content', 'user_reports',
       'is_reddit_media_domain', 'is_meta', 'link_flair_text', 'can_mod_post',
       'score', 'is_created_from_ads_ui', 'author_premium', 'thumbnail',
       'edited', 'author_flair_css_class', 'author_flair_richtext', 'is_self',
       'created', 'link_flair_type', 'wls', 'author_flair_type', 'domain',
       'allow_live_comments', 'selftext_html', 'suggested_sort', 'archived',
       'no_follow', 'is_crosspostable', 'pinned', 'over_18', 'all_awardings',
       'awarders', 'media_only', 'can_gild', 'spoiler', 'locked',
       'author_flair_text', 'treatment_tags', 'visited', 'subreddit_id',
       'author_is_blocked', 'link_flair_background_color', 'id',
       'is_robot_indexable', 'author', 'num_comments', 'send_replies',
       'contest_mode', 'mod_reports', 'author_patreon_flair',
       'author_flair_text_color', 'permalink', 'stickied', 'url',
       'subreddit_subscribers', 'created_utc', 'num_crossposts', 'is_video',
       'post_hint', 'url_overridden_by_dest', 'preview.images',
       'preview.enabled', 'link_flair_template_id'],
      dtype='object')

In [48]:
print("final data shape : " , df.shape)

final data shape :  (8799, 85)

In [51]:
df.to_csv("../Data/reddit_cleaned.csv", index=False)
df.to_json("../Data/reddit_cleaned.json", orient="records", lines=True)